// <auto-generated />
using Core.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core.Migrations
{
    [DbContext(typeof(OnlineDatabaseContext))]
    [Migration("20190929094154_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Tables.IstekveSikayet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IstekSikayet")
                        .IsRequired();

                    b.Property<string>("KullaniciAdi")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("IstekveSikayet");
                });

            modelBuilder.Entity("Core.Tables.Kelimeler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kelime")
                        .IsRequired();

                    b.Property<string>("KelimeAnlami")
                        .IsRequired();

                    b.Property<int>("KullanicilarId");

                    b.Property<bool>("isOKey");

                    b.HasKey("Id");

                    b.HasIndex("KullanicilarId");

                    b.ToTable("Kelimeler");
                });

            modelBuilder.Entity("Core.Tables.Kullanicilar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KullaniciAdi")
                        .IsRequired();

                    b.Property<bool>("isOKey");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("Core.Tables.Kelimeler", b =>
                {
                    b.HasOne("Core.Tables.Kullanicilar", "Kullanicilar")
                        .WithMany()
                        .HasForeignKey("KullanicilarId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
